### ISSUE TITLE
Impossible to rotate map

### ISSUE THREAD

**Issue by Emirom315** [GlowPuff/ImperialCommander2#148]
In the android version, when tapping with three fingers to rotate the map, the following error appears:

![Image](https://github.com/user-attachments/assets/cb77a393-aeb1-44cf-8cf2-0075a740fc66)

I can tap out of that window and continue the mission, but it's impossible to rotate the map.

**Comment by GlowPuff** [comment]
Thank you for the report - I will look into this just as soon as I have some time. 🙏🏻

**Comment by GlowPuff** [comment]
I don't have an Android device to test this, but it *should* be fixed in the new update I just published.

**Comment by Emirom315** [comment]
Thanks! I tried both in my tablet and my phone, and the map can be rotated in the tablet, but the problem persists in my phone. I don't know if this could be related, but when I tap and drag with three fingers in my phone, it takes a screenshot. However, I disabled that gesture and still can't rotate the map.
